name: Linter

on:
  push:

jobs:
    run-linter:
        name: Run Linter
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2

            - name: Install Dependencies
              run: bun install

            - name: Run Linter
              run: bun lint